c:\atomsophy\Python310\python.exe: can't open file 'H:\\CAMBALACHE\\lianbot\\lianbot_docs.py': [Errno 2] No such file or directory
-------------------------------------------- 
vie 07/25/2025 22:00:56.36 - Launching LianBot 
c:\atomsophy\Python310\python.exe: can't open file 'H:\\CAMBALACHE\\lianbot\\lianbot_docs.py': [Errno 2] No such file or directory
-------------------------------------------- 
vie 07/25/2025 22:01:36.11 - Launching LianBot 
 * Serving Flask app 'lian_docs'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 352-493-878
127.0.0.1 - - [25/Jul/2025 22:01:37] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [25/Jul/2025 22:02:20] "POST /list_documents HTTP/1.1" 400 -
127.0.0.1 - - [25/Jul/2025 22:02:28] "POST /list_documents HTTP/1.1" 400 -
127.0.0.1 - - [25/Jul/2025 22:02:44] "POST /list_documents HTTP/1.1" 400 -
127.0.0.1 - - [25/Jul/2025 22:04:07] "POST /list_documents HTTP/1.1" 200 -
127.0.0.1 - - [25/Jul/2025 22:04:07] "POST /list_documents HTTP/1.1" 200 -
127.0.0.1 - - [25/Jul/2025 22:04:07] "POST /list_documents HTTP/1.1" 200 -
127.0.0.1 - - [25/Jul/2025 22:04:08] "POST /list_documents HTTP/1.1" 200 -
