c:\atomsophy\Python310\python.exe: can't open file 'H:\\CAMBALACHE\\lianbot_docs.py': [Errno 2] No such file or directory
2025-07-25 22:11:44,254 - INFO - \u25b6\ufe0f CAMBALACHE Environment Check Started
2025-07-25 22:11:44,255 - INFO - \U0001f4c1 Created missing folder: bin
2025-07-25 22:11:44,256 - INFO - \U0001f4c1 Created missing folder: bots
2025-07-25 22:11:44,287 - INFO - \U0001f4c1 Created missing folder: data/indexados
2025-07-25 22:11:44,287 - INFO - \U0001f4c1 Created missing folder: configs
-------------------------------------------- 
vie 07/25/2025 22:25:34.07 - Launching LianBot 
Traceback (most recent call last):
  File "H:\CAMBALACHE\lianbot\lian_docs.py", line 1, in <module>
    from flask import Flask, render_template_string, request, jsonify
ModuleNotFoundError: No module named 'flask'
-------------------------------------------- 
vie 07/25/2025 22:43:05.85 - Launching LianBot 
 * Serving Flask app 'lian_docs'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 142-988-350
127.0.0.1 - - [25/Jul/2025 22:43:06] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [25/Jul/2025 22:43:38] "POST /list_documents HTTP/1.1" 200 -
127.0.0.1 - - [25/Jul/2025 22:43:38] "POST /list_documents HTTP/1.1" 200 -
127.0.0.1 - - [25/Jul/2025 22:43:38] "POST /list_documents HTTP/1.1" 200 -
127.0.0.1 - - [25/Jul/2025 22:43:38] "POST /list_documents HTTP/1.1" 200 -
